### ISSUE TITLE
'given.filter is not a function'

### ISSUE THREAD

**Issue by Schwartz10** [3box/identity-wallet-js#68]
Not sure if this is a bug in the identity-wallet or js-did, but generally, I _think_ this is how to replicate this bug (this is a _much_ simpler version of my code). Two instances of IdentityWallets, 2 instances of js-did, where the identity wallet provider is created from the same `seed` and the `getPermission` functions start and finish in reverse order, see pseudo code:

```js
const seed = '0x1';
const idWallet1 = await IdentityWallet.create({
    seed,
   // the idea is that this getPermission will get invoked first, but resolve second
    getPermission: () => new Promise((resolve) => setTimeout(() => resolve(true), 5000))
});

const idWallet2 = await IdentityWallet.create({
    seed,
   // this getPermission func will get invoked second, but resolve first
    getPermission: async () => true,
});

func authDid1() {
       const did1 = new DID({ provider: idWallet1.getDidProvider() });
       return did1.authenticate();
}

func authDid2() {
       const did2 = new DID({ provider: idWallet2.getDidProvider() });
       return did2.authenticate();
}

try {
  Promise.all([authDid1(), authDid2()])
} catch (err) {
  /*
  From getPermission invoked by authDid1
 
    Unhandled handler error {
  jsonrpc: '2.0',
  id: '5I2y9c5YTiktjHfUa5aMp',
  method: 'did_authenticate',
  params: undefined
} TypeError: given.filter is not a function
    at Permissions.<anonymous> (/Users/jonathanschwartz/Documents/owl/streams/identity-manager/node_modules/identity-wallet/lib/permissions.js:47:53)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jonathanschwartz/Documents/owl/streams/identity-manager/node_modules/identity-wallet/lib/permissions.js:5:58)
*/
}

```

Happy to share the actual code i'm writing if thats more helpful

**Comment by oed** [comment]
The function signature of the `getPermission` function has changed. It now needs to return an array:

```ts
interface PermissionRequest {
  type: string
  origin?: string | null
  payload: Record<string, any>
}

async function getPermission(req: PermissionRequest): Array<string>
```

The payload will contain an object with the property `paths` which is an array of strings. The function needs to return which of these paths it grants permissions to.
